// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'superstruct', kind: "module", path: './superstruct.html', attributes: []},
{name: 'superstruct.SuperStruct', kind: "structdeclaration", path: './superstruct/SuperStruct.html', attributes: []},
{name: 'superstruct.SuperStruct.this', kind: "functiondeclaration", path: './superstruct/SuperStruct.this.html', attributes: []},
];
