// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'superstruct', kind: "module", path: './superstruct.html', attributes: []},
{name: 'superstruct.pick', kind: "functiondeclaration", path: './superstruct/pick.html', attributes: ["auto"]},
{name: 'superstruct.pickAmong', kind: "functiondeclaration", path: './superstruct/pickAmong.html', attributes: ["auto"]},
{name: 'superstruct.SuperStruct', kind: "structdeclaration", path: './superstruct/SuperStruct.html', attributes: []},
{name: 'superstruct.SuperStruct.opAssign', kind: "functiondeclaration", path: './superstruct/SuperStruct.opAssign.html', attributes: ["auto"]},
{name: 'superstruct.SuperStruct.opBinary', kind: "functiondeclaration", path: './superstruct/SuperStruct.opBinary.html', attributes: ["auto"]},
{name: 'superstruct.SuperStruct.opCall', kind: "functiondeclaration", path: './superstruct/SuperStruct.opCall.html', attributes: ["auto"]},
{name: 'superstruct.SuperStruct.opCast', kind: "functiondeclaration", path: './superstruct/SuperStruct.opCast.html', attributes: ["auto"]},
{name: 'superstruct.SuperStruct.opCmp', kind: "functiondeclaration", path: './superstruct/SuperStruct.opCmp.html', attributes: ["auto"]},
{name: 'superstruct.SuperStruct.opDollar', kind: "functiondeclaration", path: './superstruct/SuperStruct.opDollar.html', attributes: ["auto"]},
{name: 'superstruct.SuperStruct.opEquals', kind: "functiondeclaration", path: './superstruct/SuperStruct.opEquals.html', attributes: []},
{name: 'superstruct.SuperStruct.opIndex', kind: "functiondeclaration", path: './superstruct/SuperStruct.opIndex.html', attributes: ["auto"]},
{name: 'superstruct.SuperStruct.opOpAssign', kind: "functiondeclaration", path: './superstruct/SuperStruct.opOpAssign.html', attributes: ["auto"]},
{name: 'superstruct.SuperStruct.opSlice', kind: "functiondeclaration", path: './superstruct/SuperStruct.opSlice.html', attributes: ["auto"]},
{name: 'superstruct.SuperStruct.opUnary', kind: "functiondeclaration", path: './superstruct/SuperStruct.opUnary.html', attributes: ["auto"]},
{name: 'superstruct.SuperStruct.this', kind: "functiondeclaration", path: './superstruct/SuperStruct.this.html', attributes: []},
];
